name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  JAVA_VERSION: 11

jobs:
  format_compile_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup SBT
        uses: coursier/setup-action@v1.3
        with:
          jvm: temurin:${{env.JAVA_VERSION}}
          apps: sbt
      - name: Check format
        run: sbt checkFormat
      - name: Scalafix Lint
        run: sbt scalafixLint
      - name: Scapegoat Lint
        run: sbt scapegoatLint
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup SBT
        uses: coursier/setup-action@v1.3
        with:
          jvm: temurin:${{env.JAVA_VERSION}}
          apps: sbt
      - name: Run tests with coverage Report
        run: sbt testCoverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  dependency-review:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
