name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-build-and-lint:
    uses: ./.github/workflows/build-and-lint.yml

  call-unit-tests:
    needs: call-build-and-lint
    uses: ./.github/workflows/test.yml
