name: Test & Coverage

on:
  workflow_call
  secrets:
    codecov-token:
      description: The Webhook URL for the codecov-token channel
      required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: VirtusLab/scala-cli-setup@v0.2.1
        with:
          jvm: adopt:11
      - name: Run tests with coverage Report
        run: sbt testCoverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.codecov-token }}
          fail_ci_if_error: true